### ISSUE TITLE
Instant death

### ISSUE THREAD

**Issue by Dr-Jerm** [aframevr/a-blast#108]
I'm pretty sure the game isn't supposed to be this hard? Upon loading in and shooting the start enemy two enemies spawn and instantly kill me. I've been unsuccessful dodging. I'm using Chromium Version 56.0.2902.0 (64-bit) 

Here's a video: https://gfycat.com/UniformDeepChevrotain

**Comment by ngokevin** [comment]
Try using Chromium from September 24th. The latest Chromium has a nasty bug where animations run 1000x too fast.

**Comment by Dr-Jerm** [comment]
It worked great on Firefox!

**Comment by fernandojsg** [comment]
It should be fixed now, I've tried in both browsers and it's working as expected
